Remove -out parameter
This is not used anywhere as far as I can tell and prevents the orb being used with Terraform cloud

```
Error: Saving a generated plan is currently not supported

The "remote" backend does not support saving the generated execution plan
locally at this time.
```